name: Main Deployment

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Run App
        uses: appleboy/ssh-action@0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            PATH=$PATH:/${{ secrets.SSH_USERNAME }}/.nvm/versions/node/v18.12.1/bin
            cd /root/projects/wilayah-nusantara/apps/api
            git checkout main
            git pull origin main
            pnpm install
            pnpm build
            pnpm mikro-orm:prod migration:up
            pm2 start 0
        
